package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "my_app",
    srcs = [
        "config.h",
        "my_app.c",
    ],
    visibility = ["//visibility:public"],
    deps = ["@org_iota_client//cclient/api"],
)
